language: php

php:
   - 7.0

install:
   - composer install
   - composer require satooshi/php-coveralls:1.*

script:
   - vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover tests/logs/clover.xml
   - vendor/bin/behat --config tests/behat.yml

after_success:
   - mkdir -p build/logs
   - vendor/bin/coveralls -v --coverage_clover=tests/logs/clover.xml
